FROM python:3.12.3

WORKDIR /app

RUN pip3 install --upgrade pip
RUN pip3 install --upgrade setuptools
RUN pip3 install --upgrade wheel

COPY ./flask_app/requirements.txt /app/requirements.txt
RUN pip install -v --no-cache-dir -r /app/requirements.txt
COPY ./flask_app/ /app/

CMD ["python3", "/app/app.py"]
