FROM apache/airflow:2.9.0-python3.9

USER root
RUN pip3 install --upgrade pip

# RUN pip3 install apache-airflow-providers-apache-spark
# RUN pip3 install apache-airflow-providers-http

USER airflow
COPY ./airflow/dags /opt/airflow/dags
RUN airflow db init
RUN airflow db migrate
RUN airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin

CMD ["bash", "-c", "airflow scheduler & airflow webserver"]