FROM python:3.9-slim

WORKDIR /app

USER root
RUN apt-get update 
RUN apt-get install libssl-dev
RUN apt-get install -y build-essential 
RUN apt-get install -y python3-dev
RUN apt-get install -y cython3

RUN pip3 install --upgrade pip
RUN pip3 install --upgrade setuptools
RUN pip3 install --upgrade wheel

COPY ./streaming_layer/* /app/
COPY ./trained_model/* /app/trained_model/
RUN pip install -v --no-cache-dir -r /app/requirements.txt

CMD ["python", "/app/streaming_job.py"]
